
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-functional",
  "version": "0.0.1",
  "versions": {
    "@openai/agents-functional": "0.0.1",
    "@openai/agents-core": "workspace:*",
    "@openai/agents-openai": "workspace:*",
    "@openai/agents-realtime": "workspace:*",
    "@openai/zod": "npm:zod@^3.25.40"
  }
};

export default METADATA;
